version: '3.8'

services:
  backend:
    container_name: fbi-wanted-api
    env_file:
      - .env
    build:
      context: ./fbi-wanted-api
      dockerfile: Dockerfile
    network_mode: "host"  # ✅ Uses host network, so no port mapping needed
    volumes:
      - backend_node_modules:/app/node_modules
    depends_on:
      - redis
    stdin_open: true
    tty: true
    environment:
      REDIS_HOST: host.docker.internal  # ✅ use this if backend connects to Redis via env

  frontend:
    container_name: fbi-wanted-frontend
    platform: linux/amd64
    build:
      context: ./fbi-wanted-frontend
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - ./fbi-wanted-frontend:/app:cached
      - frontend_node_modules:/app/node_modules
    stdin_open: true
    tty: true

  redis:
    image: redis:7
    container_name: fbi-redis
    network_mode: "host"
    command: ["redis-server", "--bind", "0.0.0.0"]  # ✅ Allow all interfaces
    # No ports needed due to host networking

volumes:
  backend_node_modules:
  frontend_node_modules:
